[workspace]
resolver = "2"
members = [
  "sdml-parser",
  "schema-transpiler",
  
  # graphql_value and graphql_parser are forked from (https://github.com/async-graphql/async-graphql)
  # and modified for kv_graph_ql.
  "graphql-value",
  "graphql-parser",
]

[workspace.dependencies]
graphql-parser = { path = "graphql-parser", version = "7.0.6" }
graphql-value = { path = "graphql-value", version = "7.0.6" }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
indexmap = { version = "2", features = ["serde"] }
bytes = { version = "1.6.0", features = ["serde"] }