[package]
name = "db_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
sdml_parser.workspace = true
graphql_parser.workspace = true
graphql_value.workspace = true

async-trait.workspace = true
foundationdb = {version = "0.9.1", features = [
  "fdb-7_3"
]}
